# Generated by Django 6.0.7 on 2026-07-26 12:50

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Animal ID')),
                ('name', models.CharField(max_length=80)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=10)),
                ('breed', models.CharField(blank=True, default='', max_length=80)),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Unknown')], default='u', max_length=1)),
                ('estimated_birth_date', models.DateField(help_text='Derived from estimated age at intake; drives the medical timeline.')),
                ('intake_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('intake', 'Intake'), ('medical_hold', 'Medical Hold'), ('foster', 'In Foster'), ('available', 'Available'), ('pending', 'Pending'), ('adopted', 'Adopted')], default='intake', max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('description', models.TextField(blank=True, default='', help_text='Public-facing bio.')),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-intake_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_type', models.CharField(choices=[('foster', 'Foster'), ('adoption', 'Adoption')], max_length=10)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='animals.animal')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
