# Generated by Django 6.0.7 on 2026-07-26 17:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FosterCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('checked_by', models.CharField(blank=True, default='', max_length=80)),
                ('notes', models.CharField(blank=True, default='', help_text='e.g. “Texted foster, all well.”', max_length=300)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='animals.placement')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
