# Generated by Django 6.0.7 on 2026-07-26 17:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0003_fostercheckin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('medication', 'Medication'), ('appointment', 'Appointment'), ('checkin', 'Check-in')], max_length=15)),
                ('ref_id', models.PositiveIntegerField()),
                ('channel', models.CharField(default='sms', max_length=10)),
                ('body', models.TextField(blank=True, default='')),
                ('sent_by', models.CharField(blank=True, default='', max_length=80)),
                ('sent_date', models.DateField(default=datetime.date.today)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders_sent', to='animals.placement')),
            ],
            options={
                'ordering': ['-sent_date'],
                'unique_together': {('kind', 'ref_id', 'placement', 'sent_date')},
            },
        ),
    ]
