# Generated by Django 6.0.7 on 2026-07-26 12:50

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('species', models.CharField(blank=True, default='', help_text="Limit to 'dog' or 'cat'; blank = all species.", max_length=10)),
                ('mandatory_for_available', models.BooleanField(default=False, help_text='If set, animals cannot be marked Available until this is completed.')),
                ('sort', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('dosage', models.CharField(blank=True, default='', max_length=80)),
                ('frequency', models.CharField(default='Once daily', max_length=80)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instructions', models.CharField(blank=True, default='', max_length=200)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='animals.animal')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text='e.g. “DHPP #2”', max_length=100)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('completed_by', models.CharField(blank=True, default='', max_length=80)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('auto_generated', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_events', to='animals.animal')),
                ('milestone_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='medical.milestonetype')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='MedLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('given', models.BooleanField(default=False)),
                ('logged_by', models.CharField(blank=True, default='', max_length=80)),
                ('note', models.CharField(blank=True, default='', help_text='e.g. “foster texted 8:15am”', max_length=200)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='medical.medication')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('medication', 'date')},
            },
        ),
    ]
