# Generated by Django 6.0.7 on 2026-07-26 17:29

import django.db.models.deletion
import django.utils.timezone
import medical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_fostercheckin'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=medical.models.record_upload_path)),
                ('label', models.CharField(blank=True, default='', help_text='e.g. “Spay discharge paperwork”', max_length=120)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=80)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='animals.animal')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='MedLogEntry',
        ),
    ]
