# Generated by Django 6.0.7 on 2026-07-26 12:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. “The Rivera Household”', max_length=120, verbose_name='Household name')),
                ('primary_first_name', models.CharField(max_length=60)),
                ('primary_last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('state', models.CharField(blank=True, default='NC', max_length=2)),
                ('zip_code', models.CharField(blank=True, default='', max_length=10)),
                ('home_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment / Condo'), ('mobile', 'Mobile home'), ('other', 'Other')], default='house', max_length=20)),
                ('owns_home', models.BooleanField(default=True)),
                ('has_fenced_yard', models.BooleanField(default=False)),
                ('environment_notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('capability', 'Capability'), ('environment', 'Environment'), ('other', 'Other')], default='capability', max_length=20)),
                ('auto_rule_key', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('foster', 'Foster'), ('adoption', 'Adoption')], max_length=10)),
                ('stage', models.CharField(choices=[('new', 'New Application'), ('review', 'Under Review'), ('interview', 'Interview'), ('approved', 'Approved / Matched'), ('inactive', 'Inactive')], default='new', max_length=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(blank=True, help_text='Animal of interest, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='animals.animal')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='people.household')),
            ],
            options={
                'ordering': ['stage', 'sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('relationship', models.CharField(blank=True, default='', help_text='e.g. spouse, roommate', max_length=60)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='people.household')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('species', models.CharField(max_length=40)),
                ('age_years', models.PositiveIntegerField(blank=True, null=True)),
                ('spayed_neutered', models.BooleanField(default=False)),
                ('up_to_date_vaccines', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_pets', to='people.household')),
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='households', to='people.tag'),
        ),
    ]
